module.exports = {table:
{
  "*[,,shapeAssociation]" : {
     ",": ["[,,shapeAssociation]","*[,,shapeAssociation]"], 
     "$": []}, 
  "?[^,^,iri]" : {
     "^": ["[^,^,iri]"], 
     "AT_START": [], 
     "AT_IRI_REF": [], 
     "}": []}, 
  "[,,shapeAssociation]" : {
     ",": [",","shapeAssociation"]}, 
  "[[{,FOCUS,iri,or([objectTerm,_]),}],[{,or([subjectTerm,_]),iri,FOCUS,}]]" : {
     "{": ["[{,FOCUS,iri,or([objectTerm,_]),}]","[{,or([subjectTerm,_]),iri,FOCUS,}]"]}, 
  "[^,^,iri]" : {
     "^": ["^","^","iri"]}, 
  "[{,FOCUS,iri,or([objectTerm,_]),}]" : {
     "{": ["{","FOCUS","iri","or([objectTerm,_])","}"]}, 
  "[{,or([subjectTerm,_]),iri,FOCUS,}]" : {
     "{": ["{","or([subjectTerm,_])","iri","FOCUS","}"]}, 
  "booleanLiteral" : {
     "TRUE": ["or([TRUE,FALSE])"], 
     "FALSE": ["or([TRUE,FALSE])"]}, 
  "iri" : {
     "IRI_REF": ["IRI_REF"]}, 
  "langString" : {
     "LANG_STRING_LITERAL1": ["LANG_STRING_LITERAL1"], 
     "LANG_STRING_LITERAL_LONG1": ["LANG_STRING_LITERAL_LONG1"], 
     "LANG_STRING_LITERAL2": ["LANG_STRING_LITERAL2"], 
     "LANG_STRING_LITERAL_LONG2": ["LANG_STRING_LITERAL_LONG2"]}, 
  "literal" : {
     "INTEGER": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DECIMAL": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "DOUBLE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "TRUE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "FALSE": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL_LONG1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "LANG_STRING_LITERAL_LONG2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG1": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"], 
     "STRING_LITERAL_LONG2": ["or([rdfLiteral,numericLiteral,booleanLiteral])"]}, 
  "nodeSelector" : {
     "A_TOKEN": ["objectTerm"], 
     "IRI_REF": ["objectTerm"], 
     "INTEGER": ["objectTerm"], 
     "DECIMAL": ["objectTerm"], 
     "DOUBLE": ["objectTerm"], 
     "TRUE": ["objectTerm"], 
     "FALSE": ["objectTerm"], 
     "LANG_STRING_LITERAL1": ["objectTerm"], 
     "LANG_STRING_LITERAL_LONG1": ["objectTerm"], 
     "LANG_STRING_LITERAL2": ["objectTerm"], 
     "LANG_STRING_LITERAL_LONG2": ["objectTerm"], 
     "STRING_LITERAL1": ["objectTerm"], 
     "STRING_LITERAL_LONG1": ["objectTerm"], 
     "STRING_LITERAL2": ["objectTerm"], 
     "STRING_LITERAL_LONG2": ["objectTerm"], 
     "{": ["triplePattern"]}, 
  "numericLiteral" : {
     "INTEGER": ["INTEGER"], 
     "DECIMAL": ["DECIMAL"], 
     "DOUBLE": ["DOUBLE"]}, 
  "objectTerm" : {
     "A_TOKEN": ["subjectTerm"], 
     "IRI_REF": ["subjectTerm"], 
     "INTEGER": ["literal"], 
     "DECIMAL": ["literal"], 
     "DOUBLE": ["literal"], 
     "TRUE": ["literal"], 
     "FALSE": ["literal"], 
     "LANG_STRING_LITERAL1": ["literal"], 
     "LANG_STRING_LITERAL_LONG1": ["literal"], 
     "LANG_STRING_LITERAL2": ["literal"], 
     "LANG_STRING_LITERAL_LONG2": ["literal"], 
     "STRING_LITERAL1": ["literal"], 
     "STRING_LITERAL_LONG1": ["literal"], 
     "STRING_LITERAL2": ["literal"], 
     "STRING_LITERAL_LONG2": ["literal"]}, 
  "or([TRUE,FALSE])" : {
     "TRUE": ["TRUE"], 
     "FALSE": ["FALSE"]}, 
  "or([[[{,FOCUS,iri,or([objectTerm,_]),}],[{,or([subjectTerm,_]),iri,FOCUS,}]]])" : {
     "{": ["[[{,FOCUS,iri,or([objectTerm,_]),}],[{,or([subjectTerm,_]),iri,FOCUS,}]]"]}, 
  "or([langString,string])" : {
     "LANG_STRING_LITERAL1": ["langString"], 
     "LANG_STRING_LITERAL_LONG1": ["langString"], 
     "LANG_STRING_LITERAL2": ["langString"], 
     "LANG_STRING_LITERAL_LONG2": ["langString"], 
     "STRING_LITERAL1": ["string"], 
     "STRING_LITERAL_LONG1": ["string"], 
     "STRING_LITERAL2": ["string"], 
     "STRING_LITERAL_LONG2": ["string"]}, 
  "or([objectTerm,_])" : {
     "A_TOKEN": ["objectTerm"], 
     "IRI_REF": ["objectTerm"], 
     "INTEGER": ["objectTerm"], 
     "DECIMAL": ["objectTerm"], 
     "DOUBLE": ["objectTerm"], 
     "TRUE": ["objectTerm"], 
     "FALSE": ["objectTerm"], 
     "LANG_STRING_LITERAL1": ["objectTerm"], 
     "LANG_STRING_LITERAL_LONG1": ["objectTerm"], 
     "LANG_STRING_LITERAL2": ["objectTerm"], 
     "LANG_STRING_LITERAL_LONG2": ["objectTerm"], 
     "STRING_LITERAL1": ["objectTerm"], 
     "STRING_LITERAL_LONG1": ["objectTerm"], 
     "STRING_LITERAL2": ["objectTerm"], 
     "STRING_LITERAL_LONG2": ["objectTerm"], 
     "_": ["_"]}, 
  "or([rdfLiteral,numericLiteral,booleanLiteral])" : {
     "LANG_STRING_LITERAL1": ["rdfLiteral"], 
     "LANG_STRING_LITERAL_LONG1": ["rdfLiteral"], 
     "LANG_STRING_LITERAL2": ["rdfLiteral"], 
     "LANG_STRING_LITERAL_LONG2": ["rdfLiteral"], 
     "STRING_LITERAL1": ["rdfLiteral"], 
     "STRING_LITERAL_LONG1": ["rdfLiteral"], 
     "STRING_LITERAL2": ["rdfLiteral"], 
     "STRING_LITERAL_LONG2": ["rdfLiteral"], 
     "INTEGER": ["numericLiteral"], 
     "DECIMAL": ["numericLiteral"], 
     "DOUBLE": ["numericLiteral"], 
     "TRUE": ["booleanLiteral"], 
     "FALSE": ["booleanLiteral"]}, 
  "or([subjectTerm,_])" : {
     "A_TOKEN": ["subjectTerm"], 
     "IRI_REF": ["subjectTerm"], 
     "_": ["_"]}, 
  "rdfLiteral" : {
     "LANG_STRING_LITERAL1": ["or([langString,string])","?[^,^,iri]"], 
     "LANG_STRING_LITERAL_LONG1": ["or([langString,string])","?[^,^,iri]"], 
     "LANG_STRING_LITERAL2": ["or([langString,string])","?[^,^,iri]"], 
     "LANG_STRING_LITERAL_LONG2": ["or([langString,string])","?[^,^,iri]"], 
     "STRING_LITERAL1": ["or([langString,string])","?[^,^,iri]"], 
     "STRING_LITERAL_LONG1": ["or([langString,string])","?[^,^,iri]"], 
     "STRING_LITERAL2": ["or([langString,string])","?[^,^,iri]"], 
     "STRING_LITERAL_LONG2": ["or([langString,string])","?[^,^,iri]"]}, 
  "shapeAssociation" : {
     "A_TOKEN": ["nodeSelector","shapeLabel"], 
     "{": ["nodeSelector","shapeLabel"], 
     "IRI_REF": ["nodeSelector","shapeLabel"], 
     "INTEGER": ["nodeSelector","shapeLabel"], 
     "DECIMAL": ["nodeSelector","shapeLabel"], 
     "DOUBLE": ["nodeSelector","shapeLabel"], 
     "TRUE": ["nodeSelector","shapeLabel"], 
     "FALSE": ["nodeSelector","shapeLabel"], 
     "LANG_STRING_LITERAL1": ["nodeSelector","shapeLabel"], 
     "LANG_STRING_LITERAL_LONG1": ["nodeSelector","shapeLabel"], 
     "LANG_STRING_LITERAL2": ["nodeSelector","shapeLabel"], 
     "LANG_STRING_LITERAL_LONG2": ["nodeSelector","shapeLabel"], 
     "STRING_LITERAL1": ["nodeSelector","shapeLabel"], 
     "STRING_LITERAL_LONG1": ["nodeSelector","shapeLabel"], 
     "STRING_LITERAL2": ["nodeSelector","shapeLabel"], 
     "STRING_LITERAL_LONG2": ["nodeSelector","shapeLabel"]}, 
  "shapeLabel" : {
     "AT_START": ["AT_START"], 
     "AT_IRI_REF": ["AT_IRI_REF"]}, 
  "shapeMap" : {
     "A_TOKEN": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "{": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "IRI_REF": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "INTEGER": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "DECIMAL": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "DOUBLE": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "TRUE": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "FALSE": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "LANG_STRING_LITERAL1": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "LANG_STRING_LITERAL_LONG1": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "LANG_STRING_LITERAL2": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "LANG_STRING_LITERAL_LONG2": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "STRING_LITERAL1": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "STRING_LITERAL_LONG1": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "STRING_LITERAL2": ["shapeAssociation","*[,,shapeAssociation]","$"], 
     "STRING_LITERAL_LONG2": ["shapeAssociation","*[,,shapeAssociation]","$"]}, 
  "string" : {
     "STRING_LITERAL1": ["STRING_LITERAL1"], 
     "STRING_LITERAL_LONG1": ["STRING_LITERAL_LONG1"], 
     "STRING_LITERAL2": ["STRING_LITERAL2"], 
     "STRING_LITERAL_LONG2": ["STRING_LITERAL_LONG2"]}, 
  "subjectTerm" : {
     "IRI_REF": ["iri"], 
     "A_TOKEN": ["A_TOKEN"]}, 
  "triplePattern" : {
     "{": ["or([[[{,FOCUS,iri,or([objectTerm,_]),}],[{,or([subjectTerm,_]),iri,FOCUS,}]]])"]}
},

keywords:/^(FOCUS|TRUE|FALSE)/i ,

punct:/^(\^|\,|\{|\}|\_)/ ,

startSymbol:"shapeMap",
acceptEmpty:true,
}